---
- name: Disable SELinux
  hosts: homelan
  become: true
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
        policy: targeted
      notify: Reboot system

  handlers:
    - name: Reboot system
      reboot:
