---
- name: Disable firewalld
  hosts: homelan
  become: yes
  tasks:
    - name: Stop and disable firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no
